[project]
name = "buzzer-py"
version = "0.1.0"
description = "A simple real-time quiz buzzer built with Flask and Socket.IO."
readme = "README.md"
requires-python = ">=3.14,<3.15"
dependencies = [
    "eventlet",
    "flask",
    "flask-socketio",
]

[dependency-groups]
dev = [
    "mypy",
    "ruff",
    "types-flask-socketio",
]

[tool.poetry]
package-mode = false
